# Generated by Django 5.1.6 on 2025-02-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_api', '0002_alter_product_options_remove_category_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
